[api]
rate_limit = 1000
endpoint = "https://api.pro.coinbase.com"
sandbox_endpoint = "https://api-public.sandbox.pro.coinbase.com"

[order_params]
min_order_size = { "BTC/USD" = 0.001, "ETH/USD" = 0.01, "SOL/USD" = 0.1 }
price_precision = { "BTC/USD" = 2, "ETH/USD" = 2, "SOL/USD" = 4 }

[latency_optimization]
use_batch_orders = false
websocket_buffer_size = 65536