# Activates during events like FOMC announcements, CPI releases, or flash crashes
[position_sizing]
max_capital_utilization = 0.2  # Only 20% of capital deployed
per_trade_risk = 0.0025        # 0.25% risk per trade
max_leverage = 2.0             # Reduced leverage
position_cooloff = 300          # 5 min between positions

[signal_adjustments]
sentiment_weight = 0.3          # Less weight on noisy sentiment
technical_weight = 0.5
on_chain_weight = 0.2
confidence_threshold = 0.8      # Require high confidence signals
signal_decay_rate = 0.5         # Faster signal decay (50% per minute)

[execution_controls]
slippage_tolerance = 0.01       # 1% max slippage
order_type = "post_only"        # Only maker orders
size_limit_per_min = 0.05       # Max 5% of ADTV per minute
price_band = 0.05               # 5% price movement limit from last trade

[circuit_breakers]
max_drawdown = -0.02            # -2% daily loss triggers shutdown
volatility_shutdown = 0.10      # 10% 5m volatility
liquidity_alert = 0.3           # If bid-ask spread > 30bps

[fallback_strategy]
mode = "arbitrage"              # Switch to stat arb during volatility
target_markets = ["BTC/USD:USD", "BTC/USDT:USDT"]
max_arb_spread = 0.015          # 1.5% max spread capture
cooldown_after_volatility = 600 # 10 min normal volatility required to exit

[monitoring]
tick_frequency = 100            # ms between risk checks
telemetry_rate = 1              # Second between monitoring updates